# Generated by Django 5.1.2 on 2025-01-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Refund Completed', 'Refund Completed')], max_length=50),
        ),
    ]
