# Generated by Django 5.1.2 on 2025-01-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
