# Generated by Django 5.1.2 on 2025-01-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
