# Generated by Django 5.1.2 on 2025-01-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
