# Generated by Django 5.1.2 on 2025-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('conform', 'Conform'), ('Cancelled', 'Cancelled'), ('Order Processing', 'Order Processing'), ('Refund Completed', 'Refund Completed')], default='conform', max_length=50),
        ),
    ]
