# Generated by Django 5.1.2 on 2025-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_status',
            field=models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out')], default='Stock In', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('conform', 'Conform'), ('Cancelled', 'Cancelled'), ('Order Processing', 'Order Processing'), ('Delivered', 'Delivered')], default='conform', max_length=50),
        ),
    ]
