# Generated by Django 5.1.2 on 2025-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productmodel_product_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('confirm', 'Confirm'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Order Processing', max_length=50),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
