# Generated by Django 5.1.2 on 2025-02-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_order_status_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='app.seller_list'),
        ),
    ]
