# Generated by Django 5.1.2 on 2025-03-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_adoptionrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='PIN',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kanoor', 'Knoor'), ('Kasargod', 'Kasargod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikod', 'Kozhikod'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Trisure', 'Trisure'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Vayanad', 'Vayanad')], max_length=100, null=True),
        ),
    ]
