# Generated by Django 5.1.2 on 2025-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_zip_address_pin_remove_address_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
