# Generated by Django 5.1.2 on 2025-03-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_productmodel_age_productmodel_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='pet_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='pet_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
